### ISSUE TITLE
It would be nice to have default content consistent with install language choice

### ISSUE THREAD

**Issue by mose** [YesWiki/yeswiki#996] opened 2022-08-23 21:42 UTC
**Type of issue**
New feature

**Description**
It would be nice to have a default content installed according to chosen language. At the moment we only have french content in `setup/sql/default-content.sql` I wonder if we could get those useful pages translated at some point and served according to the choice made during the install process,

**Comment by J9rem** [comment] 2022-08-25 09:23
duplicate of #684 for English

**Comment by seballot** [comment] 2023-12-20 05:17
https://priorites.yeswiki.net/posts/25/possibilite-de-traduire-le-wiki-de-base

**Closed as completed by seballot** 2023-12-20 05:17 UTC

**Comment by johentsch** [comment] 2025-03-20 23:33
Seems like the issue is not resolved, only moved to a ticket tracker that's unavailable to the public?

**Comment by mrflos** [comment] 2025-03-21 10:08
It's not resolved.. ..for now but there are plans for next release 4.6 to support better i18n
